---
# Create a text file corresponding to three VLANs that you want to configure on 
# one of the four Arista switches. Choose random VLANS between 100 and 999.
# Use NAPALM and Ansible to push this configuration change (merge operation).
# Manually check the diff file before performing the commit.

- name: NAPALM vlan configuration
  hosts: pynet-sw1
  gather_facts: False
  tasks:
    - napalm_install_config:
        hostname: "{{ eapi_hostname }}"
        username: "{{ eapi_username }}"
        password: "{{ eapi_password }}"
        dev_os: eos
        config_file: vlans.txt
        commit_changes: True
        replace_config: False
        diff_file: "{{ eapi_hostname }}.diff"
        get_diffs: True
